name: Quality Build
on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/workflows/quality-build.yml"

  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/quality-build.yml"


jobs:
  quality-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # TFLint (with GCP rules)
      # -------------------------
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Setup TFLint Plugins
        working-directory: infra
        run: tflint --init

      - name: Run TFLint
        working-directory: infra
        run: tflint --recursive

      - name: Run checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra
          framework: terraform 
          skip_check: CKV_GCP_19,CKV_GCP_29,CKV_GCP_114,CKV_GCP_78,CKV_GCP_62,CKV_GCP_28 # Optional: Skip specific checks
          output_format: cli
          download_external_modules: true
          soft_fail: false  # Won't fail the build but will show warnings
